allowedOrigin: "http://localhost:4200/"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:admin}
    username: ${DB_USERNAME:postgres}
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
